# Syntax highlighting
# rougify style 'base16.solarized.light'> css/syntax.css
safe: true

highlighter:         rouge
markdown:            kramdown

# Permalinks
permalink:           pretty



# Setup
title:               An's blog
tagline:             一个 CRUD 码农的博客
description:         Welcome to my blog
author:              an
friends:
  - name: tenfy' blog
    url: https://tenfy.cn/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          /_scss
  style:            :compressed

plugins:
  - jemoji
  - jekyll-org
  - jekyll-sitemap
  - jekyll-seo-tag
  #- jekyll-toc

whitelist:
  - jemoji
  - jekyll-org
  - jekyll-sitemap
  - jekyll-seo-tag
  
