# Syntax highlighting
highlighter:         rouge
markdown:            kramdown

# Permalinks
permalink:           pretty



# Setup
title:               An's blog
tagline:             一个 CRUD 码农的博客
friends:
  - name: tenfy' blog
    url: https://tenfy.cn/

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          /_scss
  style:            :compressed

plugins:
  - jemoji
  - jekyll-org
